server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  application:
    name: component-processing-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:components
    driver-class-name: org.h2.Driver
